from typing import Protocol

from playwright.async_api import Locator
from pydantic import BaseModel, ConfigDict


class ControlFacts(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    tag_name: str
    role: str | None = None
    control_type: str | None = None
    accessible_name: str
    href: str | None = None
    test_id: str | None = None
    disabled: bool = False
    editable: bool = False
    is_form_submit: bool = False


class ControlHandler(Protocol):
    async def supports(self, locator: Locator) -> bool: ...

    async def inspect(self, locator: Locator) -> ControlFacts: ...

    def validate(self, facts: ControlFacts, expected_control: str | None) -> None: ...

    async def click(self, locator: Locator) -> None: ...


class TextFillHandler(Protocol):
    async def supports(self, locator: Locator) -> bool: ...

    async def inspect(self, locator: Locator) -> ControlFacts: ...

    def validate(self, facts: ControlFacts, expected_control: str | None) -> None: ...

    async def fill(self, locator: Locator, value: str) -> None: ...


class SubmitHandler(Protocol):
    async def supports(self, locator: Locator) -> bool: ...

    async def inspect(self, locator: Locator) -> ControlFacts: ...

    def validate(self, facts: ControlFacts, expected_control: str | None) -> None: ...

    async def submit(self, locator: Locator) -> None: ...


class SelectHandler(Protocol):
    async def supports(self, locator: Locator) -> bool: ...

    async def inspect(self, locator: Locator) -> ControlFacts: ...

    def validate(self, facts: ControlFacts, expected_control: str | None) -> None: ...

    async def select(self, locator: Locator, value: str) -> None: ...


class RadioHandler(Protocol):
    async def supports(self, locator: Locator) -> bool: ...

    async def inspect(self, locator: Locator) -> ControlFacts: ...

    def validate(self, facts: ControlFacts, expected_control: str | None) -> None: ...

    async def select(self, locator: Locator) -> None: ...


class ComboboxHandler(Protocol):
    async def supports(self, locator: Locator) -> bool: ...

    async def inspect(self, locator: Locator) -> ControlFacts: ...

    def validate(self, facts: ControlFacts, expected_control: str | None) -> None: ...

    async def open(self, locator: Locator) -> None: ...
